# Nub-IA installer for Windows (PowerShell 5.1+ / 7).
#
#   irm https://raw.githubusercontent.com/sebamar88/nub-ia/main/install.ps1 | iex
#
# Clones (or updates) the private repository over SSH into $env:NUB_IA_DIR
# (default %LOCALAPPDATA%\nub-ia\app), installs its dependencies (the
# postinstall downloads the pinned rtk binary, SHA-256 verified), and puts a
# `nub-ia` command on the user PATH via %LOCALAPPDATA%\nub-ia\bin\nub-ia.cmd.
# Idempotent: run it again to update. Never asks for elevation.
#
# Requirements: Git for Windows (Git Bash is what pi uses for its bash tool)
# with an SSH key authorised on github.com for the repo, Node.js >= 22.19, and
# pi (@earendil-works/pi-coding-agent). pnpm is used through corepack/npx when
# not installed.
$ErrorActionPreference = "Stop"

$Repo = if ($env:NUB_IA_REPO) { $env:NUB_IA_REPO } else { "git@github.com:sebamar88/nub-ia.git" }
$Branch = if ($env:NUB_IA_BRANCH) { $env:NUB_IA_BRANCH } else { "main" }
$App = if ($env:NUB_IA_DIR) { $env:NUB_IA_DIR } else { Join-Path $env:LOCALAPPDATA "nub-ia\app" }
$Bin = if ($env:NUB_IA_BIN) { $env:NUB_IA_BIN } else { Join-Path $env:LOCALAPPDATA "nub-ia\bin" }

function Say($m) { Write-Host "nub-ia installer: $m" }
function Have($c) { return [bool](Get-Command $c -ErrorAction SilentlyContinue) }

if (-not (Have git)) { throw "git is required (https://git-scm.com/download/win)." }
if (-not (Have node)) { throw "Node.js >= 22.19 is required (https://nodejs.org)." }
$v = (node -p "process.versions.node").Split(".")
if ([int]$v[0] -lt 22 -or ([int]$v[0] -eq 22 -and [int]$v[1] -lt 19)) { throw "Node.js $(node --version) is too old; Nub-IA needs >= 22.19." }
if (-not (Have pi)) {
	Say "pi is not on PATH. Installing it globally with npm..."
	npm install -g @earendil-works/pi-coding-agent
	if ($LASTEXITCODE -ne 0) { throw "could not install pi; run: npm install -g @earendil-works/pi-coding-agent" }
}

if (Test-Path (Join-Path $App ".git")) {
	Say "updating $App"
	git -C $App fetch -q origin $Branch
	git -C $App checkout -q $Branch
	git -C $App pull -q --ff-only origin $Branch
} else {
	Say "cloning $Repo into $App (SSH; your GitHub key must have access)"
	New-Item -ItemType Directory -Force -Path (Split-Path $App) | Out-Null
	git clone -q --branch $Branch $Repo $App
}
if ($LASTEXITCODE -ne 0) { throw "git failed" }

Say "installing dependencies (this downloads the pinned rtk binary)"
Push-Location $App
try {
	if (Have pnpm) { pnpm install --frozen-lockfile }
	elseif (Have corepack) { corepack pnpm install --frozen-lockfile }
	else { npx --yes pnpm@11 install --frozen-lockfile }
	if ($LASTEXITCODE -ne 0) { throw "dependency install failed" }
} finally { Pop-Location }

New-Item -ItemType Directory -Force -Path $Bin | Out-Null
$Wrapper = Join-Path $Bin "nub-ia.cmd"
@"
@echo off
rem Nub-IA launcher wrapper (generated by install.ps1). App: $App
node "$App\bin\nub-ia.mjs" %*
"@ | Set-Content -Path $Wrapper -Encoding ASCII

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if (($userPath -split ";") -notcontains $Bin) {
	[Environment]::SetEnvironmentVariable("Path", "$Bin;$userPath", "User")
	$env:Path = "$Bin;$env:Path"
	Say "added $Bin to your user PATH (open a new terminal for other windows to see it)"
}

Say "installed: $Wrapper"
Say "run: nub-ia          (first launch provisions the agent home; then /login your providers)"
Say "update later with: nub-ia update   (or rerun this installer)"
