#!/usr/bin/env sh
# Nub-IA installer for Linux and macOS.
#
#   curl -fsSL https://raw.githubusercontent.com/sebamar88/nub-ia/main/install.sh | sh
#
# Clones (or updates) the repository into $NUB_IA_DIR
# (default ~/.nub-ia/app), installs its dependencies (the postinstall downloads
# the pinned rtk binary, SHA-256 verified), and puts a `nub-ia` command on
# your PATH via a small wrapper in $NUB_IA_BIN (default ~/.local/bin).
# Idempotent: run it again to update. Never uses sudo.
#
# Requirements: git, Node.js >= 22.19, and pi (@earendil-works/pi-coding-agent).
# pnpm is used through corepack/npx when not installed.
#
# The clone uses HTTPS by default (works for a public repository with no
# setup). For a private repository, or to use your SSH key, set
#   NUB_IA_REPO=git@github.com:sebamar88/nub-ia.git   (or an ~/.ssh/config alias)
# or NUB_IA_PROTOCOL=ssh.
set -eu

GITHUB_PATH="sebamar88/nub-ia"
if [ -n "${NUB_IA_REPO:-}" ]; then
	REPO="$NUB_IA_REPO"
elif [ "${NUB_IA_PROTOCOL:-https}" = "ssh" ]; then
	REPO="git@github.com:$GITHUB_PATH.git"
else
	REPO="https://github.com/$GITHUB_PATH.git"
fi
BRANCH="${NUB_IA_BRANCH:-main}"
APP="${NUB_IA_DIR:-$HOME/.nub-ia/app}"
BIN="${NUB_IA_BIN:-$HOME/.local/bin}"
export COREPACK_ENABLE_DOWNLOAD_PROMPT=0   # corepack must not ask "Do you want to continue?" in a piped install

say() { printf 'nub-ia installer: %s\n' "$*" >&2; }
die() { say "$*"; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# Appends `export VAR=dir` + PATH line to the user's shell rc once, so new
# shells see it. Never fails the install; the current session already has
# the directory exported by the caller.
persist_path() {
	dir="$1"; var="${2:-}"; varvalue="${3:-$1}"
	for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.profile"; do
		[ -f "$rc" ] || continue
		grep -q "nub-ia installer" "$rc" 2>/dev/null && grep -q "$dir" "$rc" 2>/dev/null && continue
		{
			printf '\n# nub-ia installer\n'
			[ -n "$var" ] && printf 'export %s="%s"\n' "$var" "$varvalue"
			printf 'case ":$PATH:" in *":%s:"*) ;; *) export PATH="%s:$PATH";; esac\n' "$dir" "$dir"
		} >> "$rc" 2>/dev/null || true
	done
}

have git || die "git is required (https://git-scm.com)."
have node || die "Node.js >= 22.19 is required (https://nodejs.org)."
node -e 'const [a,b]=process.versions.node.split(".").map(Number); process.exit(a>22||(a===22&&b>=19)?0:1)' \
	|| die "Node.js $(node --version) is too old; Nub-IA needs >= 22.19."
# Package manager preference: pnpm (direct, or through corepack/npx), then npm.
# Used both for pi below and for this package's dependencies.
if have pnpm; then PM="pnpm"
elif have corepack; then PM="corepack pnpm"
elif have npx; then PM="npx --yes pnpm@11"
else PM="npm"; fi

if ! have pi; then
	say "pi (the Pi coding agent) is not on PATH. Installing it globally with ${PM%% *}…"
	if [ "$PM" = "npm" ]; then
		npm install -g @earendil-works/pi-coding-agent || die "could not install pi; install it manually: npm install -g @earendil-works/pi-coding-agent"
	else
		# pnpm refuses global installs until its global bin dir ($PNPM_HOME/bin)
		# is on PATH. Export it for this session and persist it the way
		# `pnpm setup` does, so `pi` resolves now and in new shells.
		PNPM_HOME="${PNPM_HOME:-$HOME/.local/share/pnpm}"; export PNPM_HOME
		PNPM_BIN="$PNPM_HOME/bin"
		case ":$PATH:" in *":$PNPM_BIN:"*) ;; *) PATH="$PNPM_BIN:$PATH"; export PATH;; esac
		mkdir -p "$PNPM_BIN"
		$PM add -g @earendil-works/pi-coding-agent || die "could not install pi; try: pnpm setup && pnpm add -g @earendil-works/pi-coding-agent"
		persist_path "$PNPM_BIN" PNPM_HOME "$PNPM_HOME"
	fi
fi

if [ -d "$APP/.git" ]; then
	say "updating $APP"
	git -C "$APP" fetch -q origin "$BRANCH"
	git -C "$APP" checkout -q "$BRANCH"
	git -C "$APP" pull -q --ff-only origin "$BRANCH"
else
	say "cloning $REPO into $APP"
	mkdir -p "$(dirname "$APP")"
	if ! GIT_TERMINAL_PROMPT=0 git clone -q --branch "$BRANCH" "$REPO" "$APP"; then
		case "$REPO" in
			https://*) die "clone failed. If the repository is private, use your SSH key: NUB_IA_PROTOCOL=ssh sh install.sh  (or NUB_IA_REPO=git@github.com:$GITHUB_PATH.git)";;
			*) die "clone failed over SSH: check that your GitHub key has access to $GITHUB_PATH (ssh -T git@github.com)";;
		esac
	fi
fi

say "installing dependencies (this downloads the pinned rtk binary)"
if [ "$PM" = "npm" ]; then
	(cd "$APP" && npm install)
else
	(cd "$APP" && $PM install --frozen-lockfile)
fi

mkdir -p "$BIN"
WRAPPER="$BIN/nub-ia"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env sh
# Nub-IA launcher wrapper (generated by install.sh). App: $APP
exec node "$APP/bin/nub-ia.mjs" "\$@"
EOF
chmod 0755 "$WRAPPER"

say "installed: $WRAPPER"
case ":$PATH:" in
	*":$BIN:"*) ;;
	*) persist_path "$BIN"; say "added $BIN to your shell rc; open a new terminal (or run: export PATH=\"$BIN:\$PATH\") to use nub-ia";;
esac
say "run: nub-ia          (first launch provisions ~/.nub-ia/agent; then /login your providers)"
say "update later with: nub-ia update   (or rerun this installer)"
