#!/usr/bin/env sh
# Nub-IA installer for Linux and macOS.
#
#   curl -fsSL https://raw.githubusercontent.com/sebamar88/nub-ia/main/install.sh | sh
#
# Clones (or updates) the private repository over SSH into $NUB_IA_DIR
# (default ~/.nub-ia/app), installs its dependencies (the postinstall downloads
# the pinned rtk binary, SHA-256 verified), and puts a `nub-ia` command on
# your PATH via a small wrapper in $NUB_IA_BIN (default ~/.local/bin).
# Idempotent: run it again to update. Never uses sudo.
#
# Requirements: git with an SSH key authorised on github.com for the repo,
# Node.js >= 22.19, and pi (@earendil-works/pi-coding-agent). pnpm is used
# through corepack/npx when not installed.
set -eu

REPO="${NUB_IA_REPO:-git@github.com:sebamar88/nub-ia.git}"
BRANCH="${NUB_IA_BRANCH:-main}"
APP="${NUB_IA_DIR:-$HOME/.nub-ia/app}"
BIN="${NUB_IA_BIN:-$HOME/.local/bin}"

say() { printf 'nub-ia installer: %s\n' "$*" >&2; }
die() { say "$*"; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

have git || die "git is required (https://git-scm.com)."
have node || die "Node.js >= 22.19 is required (https://nodejs.org)."
node -e 'const [a,b]=process.versions.node.split(".").map(Number); process.exit(a>22||(a===22&&b>=19)?0:1)' \
	|| die "Node.js $(node --version) is too old; Nub-IA needs >= 22.19."
if ! have pi; then
	say "pi (the Pi coding agent) is not on PATH. Installing it globally with npm…"
	npm install -g @earendil-works/pi-coding-agent || die "could not install pi; install it manually: npm install -g @earendil-works/pi-coding-agent"
fi

if [ -d "$APP/.git" ]; then
	say "updating $APP"
	git -C "$APP" fetch -q origin "$BRANCH"
	git -C "$APP" checkout -q "$BRANCH"
	git -C "$APP" pull -q --ff-only origin "$BRANCH"
else
	say "cloning $REPO into $APP (SSH; your GitHub key must have access)"
	mkdir -p "$(dirname "$APP")"
	git clone -q --branch "$BRANCH" "$REPO" "$APP"
fi

say "installing dependencies (this downloads the pinned rtk binary)"
if have pnpm; then
	(cd "$APP" && pnpm install --frozen-lockfile)
elif have corepack; then
	(cd "$APP" && corepack pnpm install --frozen-lockfile)
else
	(cd "$APP" && npx --yes pnpm@11 install --frozen-lockfile)
fi

mkdir -p "$BIN"
WRAPPER="$BIN/nub-ia"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env sh
# Nub-IA launcher wrapper (generated by install.sh). App: $APP
exec node "$APP/bin/nub-ia.mjs" "\$@"
EOF
chmod 0755 "$WRAPPER"

say "installed: $WRAPPER"
case ":$PATH:" in
	*":$BIN:"*) ;;
	*) say "add $BIN to your PATH, e.g.:  echo 'export PATH=\"$BIN:\$PATH\"' >> ~/.bashrc  (or ~/.zshrc)";;
esac
say "run: nub-ia          (first launch provisions ~/.nub-ia/agent; then /login your providers)"
say "update later with: nub-ia update   (or rerun this installer)"
