#!/usr/bin/env sh
# Nub-IA installer for Linux and macOS.
#
#   curl -fsSL https://raw.githubusercontent.com/sebamar88/nub-ia/main/install.sh | sh
#
# Clones (or updates) the repository into $NUB_IA_DIR
# (default ~/.nub-ia/app), installs its dependencies (the postinstall downloads
# the pinned rtk binary, SHA-256 verified), and puts a `nub-ia` command on
# your PATH via a small wrapper in $NUB_IA_BIN (default ~/.local/bin).
# Idempotent: run it again to update. Never uses sudo.
#
# Requirements: git, Node.js >= 22.19, and pi (@earendil-works/pi-coding-agent).
# pnpm is used through corepack/npx when not installed.
#
# The clone uses HTTPS by default (works for a public repository with no
# setup). For a private repository, or to use your SSH key, set
#   NUB_IA_REPO=git@github.com:sebamar88/nub-ia.git   (or an ~/.ssh/config alias)
# or NUB_IA_PROTOCOL=ssh.
set -eu

GITHUB_PATH="sebamar88/nub-ia"
if [ -n "${NUB_IA_REPO:-}" ]; then
	REPO="$NUB_IA_REPO"
elif [ "${NUB_IA_PROTOCOL:-https}" = "ssh" ]; then
	REPO="git@github.com:$GITHUB_PATH.git"
else
	REPO="https://github.com/$GITHUB_PATH.git"
fi
BRANCH="${NUB_IA_BRANCH:-main}"
APP="${NUB_IA_DIR:-$HOME/.nub-ia/app}"
BIN="${NUB_IA_BIN:-$HOME/.local/bin}"

say() { printf 'nub-ia installer: %s\n' "$*" >&2; }
die() { say "$*"; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

have git || die "git is required (https://git-scm.com)."
have node || die "Node.js >= 22.19 is required (https://nodejs.org)."
node -e 'const [a,b]=process.versions.node.split(".").map(Number); process.exit(a>22||(a===22&&b>=19)?0:1)' \
	|| die "Node.js $(node --version) is too old; Nub-IA needs >= 22.19."
if ! have pi; then
	say "pi (the Pi coding agent) is not on PATH. Installing it globally with npm…"
	npm install -g @earendil-works/pi-coding-agent || die "could not install pi; install it manually: npm install -g @earendil-works/pi-coding-agent"
fi

if [ -d "$APP/.git" ]; then
	say "updating $APP"
	git -C "$APP" fetch -q origin "$BRANCH"
	git -C "$APP" checkout -q "$BRANCH"
	git -C "$APP" pull -q --ff-only origin "$BRANCH"
else
	say "cloning $REPO into $APP"
	mkdir -p "$(dirname "$APP")"
	if ! GIT_TERMINAL_PROMPT=0 git clone -q --branch "$BRANCH" "$REPO" "$APP"; then
		case "$REPO" in
			https://*) die "clone failed. If the repository is private, use your SSH key: NUB_IA_PROTOCOL=ssh sh install.sh  (or NUB_IA_REPO=git@github.com:$GITHUB_PATH.git)";;
			*) die "clone failed over SSH: check that your GitHub key has access to $GITHUB_PATH (ssh -T git@github.com)";;
		esac
	fi
fi

say "installing dependencies (this downloads the pinned rtk binary)"
if have pnpm; then
	(cd "$APP" && pnpm install --frozen-lockfile)
elif have corepack; then
	(cd "$APP" && corepack pnpm install --frozen-lockfile)
else
	(cd "$APP" && npx --yes pnpm@11 install --frozen-lockfile)
fi

mkdir -p "$BIN"
WRAPPER="$BIN/nub-ia"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env sh
# Nub-IA launcher wrapper (generated by install.sh). App: $APP
exec node "$APP/bin/nub-ia.mjs" "\$@"
EOF
chmod 0755 "$WRAPPER"

say "installed: $WRAPPER"
case ":$PATH:" in
	*":$BIN:"*) ;;
	*) say "add $BIN to your PATH, e.g.:  echo 'export PATH=\"$BIN:\$PATH\"' >> ~/.bashrc  (or ~/.zshrc)";;
esac
say "run: nub-ia          (first launch provisions ~/.nub-ia/agent; then /login your providers)"
say "update later with: nub-ia update   (or rerun this installer)"
